### ISSUE TITLE
大佬怎么用呀

### ISSUE THREAD

**Issue by xiaoyuhz** [leifengwl/MoGuDing-Auto#1]
大佬怎么用

**Comment by leifengwl** [comment]
等我更新完

**Comment by leifengwl** [comment]
已更新完成

**Comment by xiaoyuhz** [comment]
好，谢谢大佬，现在测试用一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月1日(周日) 晚上6:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leifengwl/MoGuDing-Auto] 大佬怎么用呀 (#1)




 
已更新完成

**Comment by xiaoyuhz** [comment]
运行不了呀

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月1日(周日) 晚上6:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leifengwl/MoGuDing-Auto] 大佬怎么用呀 (#1)




 
已更新完成

**Comment by leifengwl** [comment]
运行日志给我看下

**Comment by xiaoyuhz** [comment]
在附件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月1日(周日) 晚上7:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leifengwl/MoGuDing-Auto] 大佬怎么用呀 (#1)




 
运行日志给我看下

**Comment by leifengwl** [comment]
看不到，直接发截图上来

**Comment by xiaoyuhz** [comment]
![Uploading IMG_20210801_195336.jpg…]()

**Comment by leifengwl** [comment]
图裂了，你那边看着正常吗？

**Comment by xiaoyuhz** [comment]
我复制给你吧

**Comment by xiaoyuhz** [comment]
https://github.com/xiaoyuhz/MoGuDing-Auto/runs/3213410960?check_suite_focus=true

**Comment by xiaoyuhz** [comment]
> 图裂了，你那边看着正常吗？

https://github.com/leifengwl/MoGuDing-Auto/issues/1#issuecomment-89050694332521打开链接就可以看到了

**Comment by leifengwl** [comment]
手动再运行一次

**Comment by leifengwl** [comment]
应该是你变量没有填写正确，json没有正常解析，有没有把注释删掉？注意json格式，看我文档里面写的

**Comment by xiaoyuhz** [comment]
[ 
&nbsp; { 
&nbsp; &nbsp; "phone": "1119", 
&nbsp; &nbsp; "password": "Ax",  
&nbsp; &nbsp; "token": "eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJtb2d1ZGluZy11c2VyIiwic3ViIjoie1wibG9naW5UeXBlXCI6XCJhbmRyb2lkXCIsXCJ1c2VySWRcIjoxMDI4MzQxODN9IiwiYXVkIjoibW9ndWRpbmciLCJleHAiOjE5NDM0MzU1NzAsIm5iZiI6MTYyNzgxNTQ3MCwiaWF0IjoxNjI3ODE2MzcwfQ.rGgCs-JqVVoBgLgEpb8pMp02eXKWyTVxDIFDpkJjL6D9wK7x4Xf77aA0r5i5IGowv3boP_yWUPusJ2kur2Ii7Q",  
&nbsp; &nbsp; "country": "中国", 
&nbsp; &nbsp; "province": "贵州省",  
&nbsp; &nbsp; "city": "贵阳市",   
&nbsp; &nbsp; "address": "贵州省·贵阳市·花果园-国际金融街3号 
",  
&nbsp; &nbsp; "latitude": "26.574949", 
&nbsp; &nbsp; "longitude": "106.693837"  
&nbsp; }, 
   



]
我复制的你的


--原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月1日(周日) 晚上8:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leifengwl/MoGuDing-Auto] 大佬怎么用呀 (#1)




 
应该是你变量没有填写正确，json没有正常解析，有没有把注释删掉？注意json格式，看我文档里面写的

**Comment by leifengwl** [comment]
后面多了个逗号，{}后面的

**Comment by xiaoyuhz** [comment]
好，谢谢我在试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月1日(周日) 晚上8:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leifengwl/MoGuDing-Auto] 大佬怎么用呀 (#1)




 
后面多了个逗号，{}后面的

**Comment by xiaoyuhz** [comment]
我改过来，重新提交了都还是不行

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月1日(周日) 晚上8:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leifengwl/MoGuDing-Auto] 大佬怎么用呀 (#1)




 
后面多了个逗号，{}后面的

**Comment by leifengwl** [comment]
看你日志应该是运行成功了，还是有问题吗？

**Comment by xiaoyuhz** [comment]
没问题，谢谢大佬，刚刚是经纬度那个符号掉到下一行了，可以用了，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月1日(周日) 晚上11:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leifengwl/MoGuDing-Auto] 大佬怎么用呀 (#1)




 
看你日志应该是运行成功了，还是有问题吗？

**Comment by leifengwl** [comment]
好的
