### ISSUE TITLE
运行成功不签到

### ISSUE THREAD

**Issue by xiaoyuhz** [leifengwl/MoGuDing-Auto#2]
不自己抓取token运行成功不签到
日志地址
https://github.com/xiaoyuhz/MoGuDing-Auto/runs/3218893994?check_suite_focus=true

**Comment by leifengwl** [comment]
推送提示的内容是什么？

**Comment by xiaoyuhz** [comment]
&gt; 欢迎使用MoGuDing-Auto!
就这个没有其他提示



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月2日(周一) 晚上6:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leifengwl/MoGuDing-Auto] 运行成功不签到 (#2)




 
推送提示的内容是什么？

**Comment by leifengwl** [comment]
使用的token还是账号密码登录的？看代码貌似没有什么问题我自己也运行成功了，建议调试下，如果会debug的话可以看下哪里出问题或者你在每个def 方法下面加一个输出语句，让我知道哪些方法运行了

**Comment by xiaoyuhz** [comment]
现在可以用了，我刚刚又重新运行了一下没有问题了

**Comment by xiaoyuhz** [comment]
我没有用token，用token一天就失效了，我把token删除了，下午运行签到不了，现在可以正常签到了，谢谢
