### ISSUE TITLE
大佬救命，我无法运行出现报错

### ISSUE THREAD

**Issue by ZFYshare** [leifengwl/MoGuDing-Auto#4]
##***group***Run python MoGuDing.py
***36;1mpython MoGuDing.py***0m
shell: /usr/bin/bash -e ***0***
env:
  pythonLocation: /opt/hostedtoolcache/Python/3.9.6/x64
  LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.6/x64/lib
  PERSONAL_INFORMATION: ***

  SERVERPUSHKEY: 
  TG_BOT_TOKEN: 
  TG_USER_ID: 
  BARK: 
  PUSHPLUS: 
  ACCESSTOKEN: 
  CORPID: 
  CORPSECRET: 
  TOUSER: 
  AGENTID: 
  THUMB_MEDIA_ID: 
  AUTHOR: 
##***endgroup***
  File "/home/runner/work/MoGuDing-Auto/MoGuDing-Auto/MoGuDing.py", line 30
    "password": "aZ27631234***"password"***,
                             ^
SyntaxError: invalid syntax
##***error***Process completed with exit code 1.

以上是出现运行报错的代码

这是我PERSONAL_INFORMATION的值
[
  {
    "phone": "1307651XXXX", 
    "password": "aZ27631234", 
    "token": "", 
    "country": "中国", 
    "province": "广东省",
    "city": "深圳市", 
    "address": "广东省 · 深圳市 · 粤商产业大厦", 
    "latitude": "22.68545", 
    "longitude": "113.951605" 
  }
  
]

**Comment by ZFYshare** [comment]
代码地址https://github.com/ZFYshare/MoGuDing-Auto/runs/3239963244?check_suite_focus=true

**Comment by leifengwl** [comment]
检查下变量内容是否正确，看报错应该是取值时出现错误

**Comment by ZFYshare** [comment]
[
&nbsp; {
&nbsp; &nbsp; "phone": "1307651XXXX",
&nbsp; &nbsp; "password": "aZ27631234",
&nbsp; &nbsp; "token": "eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJtb2d1ZGluZy11c2VyIiwic3ViIjoie1wibG9naW5UeXBlXCI6XCJhbmRyb2lkXCIsXCJ1c2VySWRcIjoxMDI2ODc2NjB9IiwiYXVkIjoibW9ndWRpbmciLCJleHAiOjE5NDM1MTE4NTAsIm5iZiI6MTYyNzg5MTc1MCwiaWF0IjoxNjI3ODkyNjUwfQ.VquSK89i5zPGylb8i-Rubm3Llrjx7Xchp6Pl_qY8aUH-pQLfE4A3qAi-xHVeky3iFecGWLay7FHkxDOrNqVKSA",
&nbsp; &nbsp; "country": "中国",
&nbsp; &nbsp; "province": "广东省",
&nbsp; &nbsp; "city": "深圳市",
&nbsp; &nbsp; "address": "广东省 · 深圳市 · 粤商产业大厦",
&nbsp; &nbsp; "latitude": "22.686386549382302",
&nbsp; &nbsp; "longitude": "113.95637797694225"
&nbsp; }

]

这是我复制关闭问题中的代码，还是依旧报同样的错误，检查过账号密码是正确的，感觉要崩溃了，启动了十多次action都是失败

**Comment by leifengwl** [comment]
看了下你的运行，还是密码取值问题，注意标点符号，建议你复制README.md中的例子，删除注释，经纬度不用精确到那么多位

**Comment by ZFYshare** [comment]
感谢回答，我发现是Actions secrets中的update之后还是原来的数值(通过改密码发现的），于是我把fork删了再重新添加secrets即可成功签到。
以下是我的代码，供大家参考
[
    {
        "phone": "1307651XXXX",
        "password": "xxxx567",
        "token": "eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJtb2d1ZGluZy11c2VyIiwic3ViIjoie1wibG9naW5UeXBlXCI6XCJhbmRyb2lkXCIsXCJ1c2VySWRcIjoxMDI2ODc2NjB9IiwiYXVkIjoibW9ndWRpbmciLCJleHAiOjE5NDM1MTE4NTAsIm5iZiI6MTYyNzg5MTc1MCwiaWF0IjoxNjI3ODkyNjUwfQ.VquSK89i5zPGylb8i-Rubm3Llrjx7Xchp6Pl_qY8aUH-pQLfE4A3qAi-xHVeky3iFecGWLay7FHkxDOrNqVKSA",
        "country": "中国",
        "province": "广东省",
        "city": "深圳市",
        "address": "广东省 · 深圳市 · 粤商产业大厦",
        "latitude": "22.68636",
        "longitude": "113.95637"
    }

]
